version: "3.8"

services:
  frontend:
    build:
      context: .
    container_name: react
    restart: unless-stopped
    networks:
      - backend-network

  reverse-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8080:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
