version: '3.8'

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
    environment:
      - PORT=4000